#!/bin/tcsh
mv ~/Downloads/G61*tsv .
table2.py "G61 request - Table1.tsv"
mv tableX.tex table1.tex
table2.py "G61 request - numbers.tsv"
mv tableX.tex numbers.tex
table2.py "G61 request - Table3.tsv"
mv tableX.tex table3.tex
#end
